var body = {
  "result" : {
    "page" : 1,
    "size" : 10,
    "videoList" : [

{
        "agreeNum" : 0,
        "collectNum" : 0,
        "status" : 0,
        "title" : "功夫龙：到指定地点燃放烟花",
        "url" : "https:\/\/qmxx.119.gov.cn\/qmxf-bucket1\/video\/SQZL\/XNTg3OTY2ODQ2NA.mp4",
        "duration" : null,
        "img" : "https:\/\/qmxx.119.gov.cn\/qmxf-bucket1\/admin\/article20220621150613734b4ec0-f566-47b2-8101-f43a26c04c8d.png",
        "companyId" : 0,
        "memo" : null,
        "disagreeNum" : 0,
        "type" : 2,
        "commentNum" : 0,
        "aliUrl" : "XNTg3OTY2ODQ2NA==",
        "videoId" : 499,
        "height" : null,
        "width" : null,
        "wxUrl" : "https:\/\/qmxx.119.gov.cn\/qmxf-bucket1\/video\/SQZL\/XNTg3OTY2ODQ2NA.mp4",
        "readNum" : null,
        "publishDate" : "2022-06-22",
        "userId" : 13380
      },
      {
        "agreeNum" : 0,
        "collectNum" : 0,
        "status" : 0,
        "title" : "功夫龙：预防电气火灾",
        "url" : "https:\/\/qmxx.119.gov.cn\/qmxf-bucket1\/video\/SQZL\/XNTg3OTY3MTI1Mg.mp4",
        "duration" : null,
        "img" : "https:\/\/qmxx.119.gov.cn\/qmxf-bucket1\/admin\/article202206211506570f21a8f0-f380-41e2-9a2d-c558ddcaf106.png",
        "companyId" : 0,
        "memo" : null,
        "disagreeNum" : 0,
        "type" : 2,
        "commentNum" : 0,
        "aliUrl" : "XNTg3OTY3MTI1Mg==",
        "videoId" : 500,
        "height" : null,
        "width" : null,
        "wxUrl" : "https:\/\/qmxx.119.gov.cn\/qmxf-bucket1\/video\/SQZL\/XNTg3OTY3MTI1Mg.mp4",
        "readNum" : null,
        "publishDate" : "2022-06-22",
        "userId" : 13380
      },
      {
        "agreeNum" : 0,
        "collectNum" : 0,
        "status" : 0,
        "title" : "功夫龙：不乱扔烟头",
        "url" : "https:\/\/qmxx.119.gov.cn\/qmxf-bucket1\/video\/SQZL\/XNTg3OTY3MDM3Mg.mp4",
        "duration" : null,
        "img" : "https:\/\/qmxx.119.gov.cn\/qmxf-bucket1\/admin\/article20220621150630c1482aa8-63f9-4760-b83e-3cda01e32e53.png",
        "companyId" : 0,
        "memo" : null,
        "disagreeNum" : 0,
        "type" : 2,
        "commentNum" : 0,
        "aliUrl" : "XNTg3OTY3MDM3Mg==",
        "videoId" : 501,
        "height" : null,
        "width" : null,
        "wxUrl" : "https:\/\/qmxx.119.gov.cn\/qmxf-bucket1\/video\/SQZL\/XNTg3OTY3MDM3Mg.mp4",
        "readNum" : null,
        "publishDate" : "2022-06-22",
        "userId" : 13380
      },

{
        "agreeNum" : 984,
        "collectNum" : 0,
        "status" : 0,
        "title" : "夏季消防公益广告3",
        "url" : "https:\/\/qmxx.119.gov.cn\/qmxf-bucket1\/video\/KPZS\/XNTg5NzE3MTUwOA.mp4",
        "duration" : null,
        "img" : "https:\/\/m.ykimg.com\/054F0601630B4AB7A81374593C035C39",
        "companyId" : null,
        "memo" : "科普知识",
        "disagreeNum" : 0,
        "type" : 0,
        "commentNum" : 0,
        "aliUrl" : "XNTg5NzE3MTUwOA==",
        "videoId" : 565,
        "height" : null,
        "width" : null,
        "wxUrl" : "https:\/\/qmxx.119.gov.cn\/qmxf-bucket1\/video\/KPZS\/XNTg5NzE3MTUwOA.mp4",
        "readNum" : null,
        "publishDate" : "2022-08-28",
        "userId" : 0
      },
      {
        "agreeNum" : 1466,
        "collectNum" : 0,
        "status" : 0,
        "title" : "夏季消防公益广告2",
        "url" : "https:\/\/qmxx.119.gov.cn\/qmxf-bucket1\/video\/KPZS\/XNTg5NzE3MDAwMA.mp4",
        "duration" : null,
        "img" : "https:\/\/m.ykimg.com\/054F0601630B4A91A8178AC98D065085",
        "companyId" : null,
        "memo" : "科普知识",
        "disagreeNum" : 0,
        "type" : 0,
        "commentNum" : 0,
        "aliUrl" : "XNTg5NzE3MDAwMA==",
        "videoId" : 564,
        "height" : null,
        "width" : null,
        "wxUrl" : "https:\/\/qmxx.119.gov.cn\/qmxf-bucket1\/video\/KPZS\/XNTg5NzE3MDAwMA.mp4",
        "readNum" : null,
        "publishDate" : "2022-08-28",
        "userId" : 0
      },
      {
        "agreeNum" : 3809,
        "collectNum" : 0,
        "status" : 0,
        "title" : "夏季消防公益广告1",
        "url" : "https:\/\/qmxx.119.gov.cn\/qmxf-bucket1\/video\/KPZS\/XNTg5NzE2OTk3Mg.mp4",
        "duration" : null,
        "img" : "https:\/\/m.ykimg.com\/054F0601630B4A6CA8134367FD02486B",
        "companyId" : null,
        "memo" : "科普知识",
        "disagreeNum" : 0,
        "type" : 0,
        "commentNum" : 0,
        "aliUrl" : "XNTg5NzE2OTk3Mg==",
        "videoId" : 563,
        "height" : null,
        "width" : null,
        "wxUrl" : "https:\/\/qmxx.119.gov.cn\/qmxf-bucket1\/video\/KPZS\/XNTg5NzE2OTk3Mg.mp4",
        "readNum" : null,
        "publishDate" : "2022-08-28",
        "userId" : 0
      },

{
        "agreeNum" : 0,
        "collectNum" : 0,
        "status" : 0,
        "title" : "花木兰之电器篇",
        "url" : "https:\/\/qmxx.119.gov.cn\/qmxf-bucket1\/video\/KPZS\/XNTg3ODQ0NjczMg.mp4",
        "duration" : null,
        "img" : "https:\/\/qmxx.119.gov.cn\/qmxf-bucket1\/admin\/article202206211606505d7c0f8f-bfa1-480d-99ca-c6b75900424f.png",
        "companyId" : 0,
        "memo" : null,
        "disagreeNum" : 0,
        "type" : 2,
        "commentNum" : 0,
        "aliUrl" : "XNTg3ODQ0NjczMg==",
        "videoId" : 504,
        "height" : null,
        "width" : null,
        "wxUrl" : "https:\/\/qmxx.119.gov.cn\/qmxf-bucket1\/video\/KPZS\/XNTg3ODQ0NjczMg.mp4",
        "readNum" : null,
        "publishDate" : "2022-06-22",
        "userId" : 13380
      },
      {
        "agreeNum" : 0,
        "collectNum" : 0,
        "status" : 0,
        "title" : "花木兰之烟头篇",
        "url" : "https:\/\/qmxx.119.gov.cn\/qmxf-bucket1\/video\/KPZS\/XNTg3OTM5NzkxMg.mp4",
        "duration" : null,
        "img" : "https:\/\/qmxx.119.gov.cn\/qmxf-bucket1\/admin\/article2022062116065232a5bd5c-8043-4bc8-a093-44c4acb64ce6.png",
        "companyId" : 0,
        "memo" : null,
        "disagreeNum" : 0,
        "type" : 2,
        "commentNum" : 0,
        "aliUrl" : "XNTg3OTM5NzkxMg==",
        "videoId" : 505,
        "height" : null,
        "width" : null,
        "wxUrl" : "https:\/\/qmxx.119.gov.cn\/qmxf-bucket1\/video\/KPZS\/XNTg3OTM5NzkxMg.mp4",
        "readNum" : null,
        "publishDate" : "2022-06-22",
        "userId" : 13380
      },
      {
        "agreeNum" : 0,
        "collectNum" : 0,
        "status" : 0,
        "title" : "居家防疫勿忘消防安全",
        "url" : null,
        "duration" : null,
        "img" : "https:\/\/qmxx.119.gov.cn\/qmxf-bucket1\/admin\/article2022062116060955276732-661b-4cb7-a953-6290ff204cb3.png",
        "companyId" : 0,
        "memo" : null,
        "disagreeNum" : 0,
        "type" : 2,
        "commentNum" : 0,
        "aliUrl" : "XNTg3ODQ0Njg1Mg==",
        "videoId" : 506,
        "height" : null,
        "width" : null,
        "wxUrl" : "t3348uovj5e",
        "readNum" : null,
        "publishDate" : "2022-06-22",
        "userId" : 13380
      }
    ],
    "articleList" : [

    ],
    "channelId" : 10,
    "total" : 57
  },
  "msg" : "succ",
  "code" : 1001
}

var obj = JSON.stringify(body);
//console.log(obj);
$done({
  body: obj,
})
