var body = {
  "result" : {
    "page" : 1,
    "size" : 10,
    "videoList" : [

{
        "agreeNum" : 0,
        "collectNum" : 0,
        "status" : 0,
        "title" : "功夫龙：到指定地点燃放烟花",
        "url" : "https:\/\/qmxx.119.gov.cn\/qmxf-bucket1\/video\/SQZL\/XNTg3OTY2ODQ2NA.mp4",
        "duration" : null,
        "img" : "https:\/\/qmxx.119.gov.cn\/qmxf-bucket1\/admin\/article20220621150613734b4ec0-f566-47b2-8101-f43a26c04c8d.png",
        "companyId" : 0,
        "memo" : null,
        "disagreeNum" : 0,
        "type" : 2,
        "commentNum" : 0,
        "aliUrl" : "XNTg3OTY2ODQ2NA==",
        "videoId" : 499,
        "height" : null,
        "width" : null,
        "wxUrl" : "https:\/\/qmxx.119.gov.cn\/qmxf-bucket1\/video\/SQZL\/XNTg3OTY2ODQ2NA.mp4",
        "readNum" : null,
        "publishDate" : "2022-06-22",
        "userId" : 13380
      },
      {
        "agreeNum" : 0,
        "collectNum" : 0,
        "status" : 0,
        "title" : "功夫龙：预防电气火灾",
        "url" : "https:\/\/qmxx.119.gov.cn\/qmxf-bucket1\/video\/SQZL\/XNTg3OTY3MTI1Mg.mp4",
        "duration" : null,
        "img" : "https:\/\/qmxx.119.gov.cn\/qmxf-bucket1\/admin\/article202206211506570f21a8f0-f380-41e2-9a2d-c558ddcaf106.png",
        "companyId" : 0,
        "memo" : null,
        "disagreeNum" : 0,
        "type" : 2,
        "commentNum" : 0,
        "aliUrl" : "XNTg3OTY3MTI1Mg==",
        "videoId" : 500,
        "height" : null,
        "width" : null,
        "wxUrl" : "https:\/\/qmxx.119.gov.cn\/qmxf-bucket1\/video\/SQZL\/XNTg3OTY3MTI1Mg.mp4",
        "readNum" : null,
        "publishDate" : "2022-06-22",
        "userId" : 13380
      },
      {
        "agreeNum" : 0,
        "collectNum" : 0,
        "status" : 0,
        "title" : "功夫龙：不乱扔烟头",
        "url" : "https:\/\/qmxx.119.gov.cn\/qmxf-bucket1\/video\/SQZL\/XNTg3OTY3MDM3Mg.mp4",
        "duration" : null,
        "img" : "https:\/\/qmxx.119.gov.cn\/qmxf-bucket1\/admin\/article20220621150630c1482aa8-63f9-4760-b83e-3cda01e32e53.png",
        "companyId" : 0,
        "memo" : null,
        "disagreeNum" : 0,
        "type" : 2,
        "commentNum" : 0,
        "aliUrl" : "XNTg3OTY3MDM3Mg==",
        "videoId" : 501,
        "height" : null,
        "width" : null,
        "wxUrl" : "https:\/\/qmxx.119.gov.cn\/qmxf-bucket1\/video\/SQZL\/XNTg3OTY3MDM3Mg.mp4",
        "readNum" : null,
        "publishDate" : "2022-06-22",
        "userId" : 13380
      },
      {
        "agreeNum" : 345,
        "collectNum" : 0,
        "status" : 0,
        "title" : "消防小子第20集",
        "url" : "https:\/\/qmxx.119.gov.cn\/qmxf-bucket1\/video\/SQZL\/XNTg5ODE4NDU2NA.mp4",
        "duration" : null,
        "img" : "https:\/\/m.ykimg.com\/054F060163100A9EA806B3BDD1073A9A",
        "companyId" : null,
        "memo" : "暑期专栏",
        "disagreeNum" : 0,
        "type" : 0,
        "commentNum" : 0,
        "aliUrl" : "XNTg5ODE4NDU2NA==",
        "videoId" : 587,
        "height" : null,
        "width" : null,
        "wxUrl" : "https:\/\/qmxx.119.gov.cn\/qmxf-bucket1\/video\/SQZL\/XNTg5ODE4NDU2NA.mp4",
        "readNum" : null,
        "publishDate" : "2022-09-01",
        "userId" : 0
      },
      {
        "agreeNum" : 356,
        "collectNum" : 0,
        "status" : 0,
        "title" : "消防小子第19集",
        "url" : "https:\/\/qmxx.119.gov.cn\/qmxf-bucket1\/video\/SQZL\/XNTg5OTU5NzY4NA.mp4",
        "duration" : null,
        "img" : "https:\/\/m.ykimg.com\/054F060163100A6EA8184F2121024329",
        "companyId" : null,
        "memo" : "暑期专栏",
        "disagreeNum" : 0,
        "type" : 0,
        "commentNum" : 0,
        "aliUrl" : "XNTg5OTU5NzY4NA==",
        "videoId" : 586,
        "height" : null,
        "width" : null,
        "wxUrl" : "https:\/\/qmxx.119.gov.cn\/qmxf-bucket1\/video\/SQZL\/XNTg5OTU5NzY4NA.mp4",
        "readNum" : null,
        "publishDate" : "2022-09-01",
        "userId" : 0
      },
      {
        "agreeNum" : 409,
        "collectNum" : 0,
        "status" : 0,
        "title" : "消防小子第18集",
        "url" : "https:\/\/qmxx.119.gov.cn\/qmxf-bucket1\/video\/SQZL\/XNTg5ODE4MzAxNg.mp4",
        "duration" : null,
        "img" : "https:\/\/m.ykimg.com\/054F060163100A43A81843B2790BFCC0",
        "companyId" : null,
        "memo" : "暑期专栏",
        "disagreeNum" : 0,
        "type" : 0,
        "commentNum" : 0,
        "aliUrl" : "XNTg5ODE4MzAxNg==",
        "videoId" : 585,
        "height" : null,
        "width" : null,
        "wxUrl" : "https:\/\/qmxx.119.gov.cn\/qmxf-bucket1\/video\/SQZL\/XNTg5ODE4MzAxNg.mp4",
        "readNum" : null,
        "publishDate" : "2022-09-01",
        "userId" : 0
      },
      {
        "agreeNum" : 499,
        "collectNum" : 0,
        "status" : 0,
        "title" : "消防小子第17集",
        "url" : "https:\/\/qmxx.119.gov.cn\/qmxf-bucket1\/video\/SQZL\/XNTg5ODE4MTU4MA.mp4",
        "duration" : null,
        "img" : "https:\/\/m.ykimg.com\/054F060163100A0FA81804448B0C827A",
        "companyId" : null,
        "memo" : "暑期专栏",
        "disagreeNum" : 0,
        "type" : 0,
        "commentNum" : 0,
        "aliUrl" : "XNTg5ODE4MTU4MA==",
        "videoId" : 584,
        "height" : null,
        "width" : null,
        "wxUrl" : "https:\/\/qmxx.119.gov.cn\/qmxf-bucket1\/video\/SQZL\/XNTg5ODE4MTU4MA.mp4",
        "readNum" : null,
        "publishDate" : "2022-09-01",
        "userId" : 0
      },
      {
        "agreeNum" : 591,
        "collectNum" : 0,
        "status" : 0,
        "title" : "消防小子第16集",
        "url" : "https:\/\/qmxx.119.gov.cn\/qmxf-bucket1\/video\/SQZL\/XNTg5ODE4MjkwMA.mp4",
        "duration" : null,
        "img" : "https:\/\/m.ykimg.com\/054F0601631009FEA817DB8B4606EC90",
        "companyId" : null,
        "memo" : "暑期专栏",
        "disagreeNum" : 0,
        "type" : 0,
        "commentNum" : 0,
        "aliUrl" : "XNTg5ODE4MjkwMA==",
        "videoId" : 583,
        "height" : null,
        "width" : null,
        "wxUrl" : "https:\/\/qmxx.119.gov.cn\/qmxf-bucket1\/video\/SQZL\/XNTg5ODE4MjkwMA.mp4",
        "readNum" : null,
        "publishDate" : "2022-09-01",
        "userId" : 0
      },
      {
        "agreeNum" : 751,
        "collectNum" : 0,
        "status" : 0,
        "title" : "消防小子第15集",
        "url" : "https:\/\/qmxx.119.gov.cn\/qmxf-bucket1\/video\/SQZL\/XNTg5ODE4Mjg3Mg.mp4",
        "duration" : null,
        "img" : "https:\/\/m.ykimg.com\/054F0601631009ACA806EE04B0045F65",
        "companyId" : null,
        "memo" : "暑期专栏",
        "disagreeNum" : 0,
        "type" : 0,
        "commentNum" : 0,
        "aliUrl" : "XNTg5ODE4Mjg3Mg==",
        "videoId" : 582,
        "height" : null,
        "width" : null,
        "wxUrl" : "https:\/\/qmxx.119.gov.cn\/qmxf-bucket1\/video\/SQZL\/XNTg5ODE4Mjg3Mg.mp4",
        "readNum" : null,
        "publishDate" : "2022-09-01",
        "userId" : 0
      },
      {
        "agreeNum" : 937,
        "collectNum" : 0,
        "status" : 0,
        "title" : "消防小子第14集",
        "url" : "https:\/\/qmxx.119.gov.cn\/qmxf-bucket1\/video\/SQZL\/XNTg5ODE4MjgwNA.mp4",
        "duration" : null,
        "img" : "https:\/\/m.ykimg.com\/054F06016310098CA817792CCD0D7C18",
        "companyId" : null,
        "memo" : "暑期专栏",
        "disagreeNum" : 0,
        "type" : 0,
        "commentNum" : 0,
        "aliUrl" : "XNTg5ODE4MjgwNA==",
        "videoId" : 581,
        "height" : null,
        "width" : null,
        "wxUrl" : "https:\/\/qmxx.119.gov.cn\/qmxf-bucket1\/video\/SQZL\/XNTg5ODE4MjgwNA.mp4",
        "readNum" : null,
        "publishDate" : "2022-09-01",
        "userId" : 0
      },
      {
        "agreeNum" : 1303,
        "collectNum" : 0,
        "status" : 0,
        "title" : "消防小子第13集",
        "url" : "https:\/\/qmxx.119.gov.cn\/qmxf-bucket1\/video\/SQZL\/XNTg5ODE4MTQ0OA.mp4",
        "duration" : null,
        "img" : "https:\/\/m.ykimg.com\/054F060163100971A81859E3CC0533F2",
        "companyId" : null,
        "memo" : "暑期专栏",
        "disagreeNum" : 0,
        "type" : 0,
        "commentNum" : 0,
        "aliUrl" : "XNTg5ODE4MTQ0OA==",
        "videoId" : 580,
        "height" : null,
        "width" : null,
        "wxUrl" : "https:\/\/qmxx.119.gov.cn\/qmxf-bucket1\/video\/SQZL\/XNTg5ODE4MTQ0OA.mp4",
        "readNum" : null,
        "publishDate" : "2022-09-01",
        "userId" : 0
      },
      {
        "agreeNum" : 2376,
        "collectNum" : 0,
        "status" : 0,
        "title" : "消防小子第12集",
        "url" : "https:\/\/qmxx.119.gov.cn\/qmxf-bucket1\/video\/SQZL\/XNTg5ODE4MTQwOA.mp4",
        "duration" : null,
        "img" : "https:\/\/m.ykimg.com\/054F06016310093CA8177A5A8D09AC9B",
        "companyId" : null,
        "memo" : "暑期专栏",
        "disagreeNum" : 0,
        "type" : 0,
        "commentNum" : 0,
        "aliUrl" : "XNTg5ODE4MTQwOA==",
        "videoId" : 579,
        "height" : null,
        "width" : null,
        "wxUrl" : "https:\/\/qmxx.119.gov.cn\/qmxf-bucket1\/video\/SQZL\/XNTg5ODE4MTQwOA.mp4",
        "readNum" : null,
        "publishDate" : "2022-09-01",
        "userId" : 0
      },
      {
        "agreeNum" : 9683,
        "collectNum" : 0,
        "status" : 0,
        "title" : "消防小子第11集",
        "url" : "https:\/\/qmxx.119.gov.cn\/qmxf-bucket1\/video\/SQZL\/XNTg5ODE4NDIzNg.mp4",
        "duration" : null,
        "img" : "https:\/\/m.ykimg.com\/054F060163100925A8184B797802197D",
        "companyId" : null,
        "memo" : "暑期专栏",
        "disagreeNum" : 0,
        "type" : 0,
        "commentNum" : 0,
        "aliUrl" : "XNTg5ODE4NDIzNg==",
        "videoId" : 578,
        "height" : null,
        "width" : null,
        "wxUrl" : "https:\/\/qmxx.119.gov.cn\/qmxf-bucket1\/video\/SQZL\/XNTg5ODE4NDIzNg.mp4",
        "readNum" : null,
        "publishDate" : "2022-09-01",
        "userId" : 0
      }
    ],
    "articleList" : [

    ],
    "channelId" : 10,
    "total" : 57
  },
  "msg" : "succ",
  "code" : 1001
}

var obj = JSON.stringify(body);
console.log(obj);
$done({
  body: obj,
})
